name: kronix
description: A high-performance, architecturally hardened web framework for Dart.
version: 0.1.0
homepage: https://github.com/garv/kronix
repository: https://github.com/garv/kronix
issue_tracker: https://github.com/garv/kronix/issues

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  shelf_static: ^1.1.2
  args: ^2.4.2
  path: ^1.8.3
  dart_jsonwebtoken: ^2.1.2
  watcher: ^1.1.0
  dotenv: ^4.2.0
  postgres: ^3.0.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
